export const LOAD_DATA_PENDING = 'LOAD_DATA_PENDING';
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAILURE = 'LOAD_DATA_FAILURE';

export const REGISTER_FEATURE = 'REGISTER_FEATURE';
export const REGISTER_DOMAINS = 'REGISTER_DOMAINS';
export const REGISTER_TARGETS = 'REGISTER_TARGETS';

export const UPDATE_FEATURE = 'UPDATE_FEATURE';
export const REMOVE_DOMAIN = 'REMOVE_DOMAIN';
